# Use postgres/example user/password credentials
version: "3.7"
services:
  postgres:
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
volumes:
  pgdata:
